Evasive Rascal: >
  Gains a permanent +2 defense from their
  small body type and, once per activation, after Fighting,
  Firing or Interacting, they may perform a free "Scamper!"
  Move (even if they have Moved). It allows them to Move
  D6" and retreat without consequences - but not charge.
Low Standing: >
  May only equip non-rare equipment.
Clenching Bite: >
  A hound has a single 1 damage biting
  strike. When a target takes damage from it, they cannot
  retreat and count as shaken until the hound is taken
  out, retreats or targets a different enemy. Hounds use
  grounded movement and can't equip anything.
Anti-Grav Motor: >
  Gains leap movement. Its "Scamper!"
  Move becomes 6" (instead of D6).
Pesky Swarm: >
  Each point of a swarm's vitality grants it a
  1 damage flue strike. Gains regen, but takes double
  damage from flame and blast weapons. Can't equip anything.
Reinforcements!: >
  Once per game, in game turn 4 or later,
  a player may bring back any lost troopers as reinforcements.
  This is always done before first activation, starting
  with the player who won initiative. The troopers are
  redeployed within proximity (3") of any friendly reinforcement
  site. However, if any enemy soldier is within proximity
  (3") of a site, reinforcements are blocked from using it
Instinctive Reactions: >
  After elites have been targeted
  by a futile Fire or Fight action, i.e. an attack that doesn't
  cause any hit or shaken effect, they may perform a 1 AP
  action of choice as a reaction, but any rolls are desperate.
Big Bulky Gun: >
  May use the Fire action twice per activation.
  However, the crew uses grounded movement and
  can't Fire after Moving in a game turn (reinforcing counts
  as Moving). They can't equip items or melee weapons and
  the strike difficulty to Fight against them is fixed at 1.
Unstoppable Juggernaut: >
  Heavies are hardened and
  have breach and grounded movement. They don't get
  shaken, except from squad abilities
Horrid Physiology: >
  Gains regen. At the start of each activation
  'select one special rule for use this game turn:'
  "-Thunderous Advance: Increases dash roll to 2D6."
  "-Dreadful Reach: May Fight against any targets within"
  3 + D6" (roll at start of activation).
  "-Terrifying Roar: May use a free Interaction (difficulty"
  0) to shake enemy soldiers within short range (9"
  "-Fierce Toss: May use a free Interaction (difficulty ="
  target's vitality) where if successful, 1 soldier wtihin
  proximity (3") may be repositioned, and shaken, to a
  playable surface within short range (9").
Big Personality: >
  Gains Vitality 2. Can equip rares.
"+1 Slot": >
  Gains an additional inventory slot
Killer K9: >
  Gains Vitality 2. The bite becoems piercing.
Exposed Target: >
  While the drone is within proximity
  (3") of enemies, they can't gain the benefit of cover,
  defense or the items chameleon weave and claoking field.
XL Drone: >
  Gains Vitality 2 and Slots 3.
Airborne Vermin: >
  Gains 9"(+D6) leap movement.
Hardened: >
  Gains the hardened universal special rule.
Leap Into Battle: >
  Gains 9"(+D6) leap movement.
Blessing of Speed: >
  Gains 9"(+2D6) grounded movement.
  Can't Defend, but gains +1 defense when Moving
  "(1 AP) and +2 defense when Dash Moving (2 AP)."
Servo Gun: >
  Allows a ranged weapon to be bought
  and attached to the mount as a servo gun.
Hyper-Active: >
  Gains AP 4. Becoming shaken reduces
  the soldier to 2 AP, instead of 1. Reactions cause by
  Instinctive Reactions no longer use desperate rolls.
Bit of Protection: >
  Gains a permanent +1 defense buff.
Thrusters & Stabilizers: >
  Gains 9"(+D6) leap movement
  and all equipped ranged weapons gain hip fire.
Ironclad: >
  Piercing weapons must roll hardened rolls
  against ironclad armour, while non-piercing weapons
  must use fluke rolls for their hardend rolls! Also, dash
  rolls are reduced to D3.
Leaping Terror: >
  Movement is changed to leap 9"(+D6).
Is That All You Got?: >
  The drill sergeant may target an expended friendly
  soldier within proximity (3"). The interaction difficulty
  is 1. If successful, the ally may immediately
  perform a 1 AP action as a reaction. On a critical
  success, they may perform a 2 AP action instead.
Tactical Reassessment: >
  The interaction difficulty is 1. If successful, the
  squad gains 1 additional squad point (SP). On a
  critical success, the squad gains 2 additional squad
  points (SP).
Specialist: >
  These skillful experts automatically succeed
  when Interacting (1 AP), and automatically
  critically succeed, if applicable, when
  Frantically Interacting (2 AP).
Master Crafter: >
  All weapons and items in a master crafter's
  squad may reroll one shot and one strike roll of 1
  during each Fire or Fight action. Additionally,
  any rare equipment that a master crafter equips
  does not count towards your total amount of rares.
Champion: >
  A champion always uses a strike difficulty of
  1 when Fighting. The only exception is when
  they are Fighting another champion, where
  normal rules are used.
Herald of Fury: >
  Friendly soldiers within short range (9")
  of the herald gain 1 extra strike with an
  equipped melee weapon (includes the herald).
Pathfinder: >
  Every game turn, just before the first activation
  the pathfinder, and any friendly soldier within
  short range (9"), may Move D6". This move
  counts as a reaction (no AP cost), but may not
  be used to charge or retreat.
Salvo Master: >
  The salvo master reduces the cost of all
  friendly Firing actions within proximity (3")
  by 1 action point (includes the master).
Lord Protector: >
  Friendly soldiers within proximity (3") of
  the lord gain 1 extra point of defense, up to
  an unheard of limit of 3 (includes the lord),
  allowing more defense than normal.
The Faceless: >
  Master of blending in and leading through
  hushed whispers. A faceless squad leader,
  and any friendly soldier within proximity (3"),
  may only be targeted by enemies when they are
  the closest visible target or when they are within
  proximity (3") of the enemy attacking.
Psymancer: >
  May choose two psychic powers.
Master Psymancer: >
  May choose three psychic powers. Also, the
  cost of Interacting is reduced by 1 action
  point (AP) when using a psychic power.
Nether Shield: >
  Using this ability, as an Interaction with a
  difficulty of 2, the psymancer provides arcane
  protection to a friendly soldier within short
  range (9"), or themselves. The shield grants a
  +1 defense (+2 on a critical success) with a
  duration of 2. Provides immunity to psychic
  powers.
The Exalted One: >
  The psymancer calls on otherworldy forces to bless
  a friendly soldier within short range (9"), or
  themselves, using an Interaction with a difficulty
  of 2. If successful, the friendly soldier gains 1
  extra action point (AP) and 1 extra point of damage
  to all their shots and strikes during their next
  activation (place a speical effects token next to
  them). However, if celestial favour is not gained
  and an interact roll of 1 is scored, the targeted
  soldier loses 1 point of vitality instead.
Summoning Call: >
  The psymancer calls on otherworldly forces
  to bless a friendly soldier within short range
  (9"), or themselves, using an Interaction with
  a difficulty of 2. If successful, the friendly soldier
  gains 1 extra action point (AP) and 1 extra point of
  damage to all their shots and strikes during their
  next activation (place a special effects token next
  to them). However, if celestial favour is not gained
  and an interact roll of 1 is scored, the targeted
  soldier loses 1 point of vitality instead.
Shatter Mind: >
  The psymancer directs vilent cosmic energy at a
  single enemy target within short range (9"),
  using an Interaction. The Interaction difficulty
  is 2. If successful, the target takes 1 point of
  piercing damage (2 if a critical success is scored).
  This attack doesn't require line-of-sight.
Wall of Torment: >
  Using an Interaction with a difficulty of 4, a
  psymancer may conjure an infernal, painful barrier
  which deals 1 point of piercing damage to enemies
  that Move through it. Choose a start and end point
  within short range (9") of each other and the psymancer.
  Use special effects tokens to mark the positions. The
  wall has a duration of 2. Only one may be activer
  per player.
Puppet Master: >
  Using an Interaction, the psymancer deviously
  attempts to influence the movement of a single
  enemy target within medium range (18"), without
  the need for line-of-sight. The interaction
  difficulty is equal to the target's current vitality.
  If successful, the target may be moved up to 3"
  or have their regular movement distance reduced
  to 3" for the rest of the game turn.
Blood Ritual: >
  In a dark ritual, an Interaction with a difficulty
  of 3, the psymancer sacrifices a friendly soldier
  within proximity (3"). If successful, remove the
  soldier as if they'd been taken out, take note
  of their current vitality. This number may be
  added to the result of all dice rolls (up to a
  maximum of 6) performed byt he squad for the rest
  of the game turn. May onlyl be used once per game.
Spirit Surge: >
  When the psymancer is about to lose thier last point
  of vitality and be taken out, an immense surge of
  ethereal energy is released, restoring the psymancer
  back to 1 point of vitality. Also, an soldier, friendly
  or enemy, within proximity (3") of the psymancer is
  knocked back D6", becoming shaken. This can only happen
  once per game.